alias: Doorbell-Chime
description: ""
mode: single
triggers:
  - entity_id:
      - binary_sensor.%entity_name%
    from: "off"
    to: "on"
    trigger: state
conditions:
  - condition: time
    after: "03:00:00"
    weekday:
      - mon
      - tue
      - wed
      - thu
      - fri
      - sat
      - sun
    before: "00:00:00"
actions:
  - sequence:
      - action: switch.turn_on
        metadata: {}
        data: {}
        target:
          entity_id: switch.%entity_name%
      - delay:
          hours: 0
          minutes: 0
          seconds: 0
          milliseconds: 250
      - action: switch.turn_off
        metadata: {}
        data: {}
        target:
          entity_id: switch.%entity_name%
